Release v6.0.8
PrestaShop/welcome pull request #147
Opened 2022-10-11 16:11 UTC by atomiix

2022-10-11 16:18 UTC, matks approved these changes

2022-10-12 08:36 UTC, yanmakouf approved these changes

2022-10-12 08:42 UTC, kpodemski commented
I'm a bit lost. What exactly is released there? :D

2022-10-12 08:48 UTC, kpodemski requested changes
I think this PR just bumps the version and release should be `dev` to `master`?

2022-10-12 09:28 UTC, atomiix commented
@kpodemski the issue in https://github.com/PrestaShop/PrestaShop/issues/29867 is that after upgrading to 8.0.0, the module welcome doesn't have its own autoloader (and cannot rely on PrestaShop's autoloader because the module has been removed from composer.json). By releasing a new version of it, this will force the upgrade of the module during the upgrade of PrestaShop and the module will contain its own autoload.
I agree that we usually merge dev into master but here dev contains other changes than just a version bump.

2022-10-12 09:41 UTC, kpodemski approved these changes

2022-10-12 09:42 UTC, kpodemski commented
Ok, thanks. I had no idea.

2022-10-12 09:43 UTC, kpodemski commented
@atomiix In that case, it doesn't need QA, right? ;-)

2022-10-12 09:57 UTC, atomiix commented
We can ask, but I agree with you, this shouldn't need QA :)

2022-10-12 09:58 UTC, kpodemski commented
cc @PrestaShop/qa-team

2022-10-12 12:34 UTC, merged